# Generated by Django 3.2.6 on 2021-08-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210822_1930'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
