# Generated by Django 3.2.6 on 2021-08-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/static/images/default/user.jpg', upload_to='avatar/', verbose_name='Avatar'),
        ),
    ]
