# Generated by Django 3.2.6 on 2021-08-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preview',
            field=models.ImageField(null=True, upload_to='images/news&blogs/', verbose_name='Превью'),
        ),
    ]
