# Generated by Django 3.2.6 on 2021-08-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_article_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(null=True, verbose_name='Время публикации'),
        ),
    ]
