# Generated by Django 3.2.6 on 2021-08-23 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 23, 12, 18, 25, 951765), verbose_name='Время публикации'),
        ),
    ]
