# Generated by Django 3.2.4 on 2021-07-26 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.PositiveIntegerField(verbose_name='id телеграма')),
                ('tel', models.CharField(max_length=20, verbose_name='Telefon')),
                ('comment', models.TextField(verbose_name='Comment for client')),
            ],
            options={
                'verbose_name': 'Инфа о клиенте',
                'verbose_name_plural': 'Инфа о клиентах',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_num', models.PositiveSmallIntegerField(verbose_name='Столы')),
                ('place', models.PositiveSmallIntegerField(verbose_name='Кол-во мест')),
                ('is_free', models.BooleanField(default=False, verbose_name='Зането Да/Нет')),
            ],
            options={
                'verbose_name': 'Заказ столика',
                'verbose_name_plural': 'Заказы столов',
                'ordering': ['is_free', 'place', 'table_num'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now=True, verbose_name='Дата заказа')),
                ('order_accept', models.DateTimeField(auto_now_add=True, verbose_name='Дата обработки заказа')),
                ('is_accept', models.BooleanField(default=False, verbose_name='Принят Да/Нет')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.reservation', verbose_name='Столик')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
