# Generated by Django 3.2.4 on 2021-08-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_products_productscategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_num', models.PositiveSmallIntegerField(verbose_name='Столы')),
                ('place', models.PositiveSmallIntegerField(verbose_name='Кол-во мест стола')),
                ('is_free', models.BooleanField(default=False, verbose_name='Статус свободности')),
            ],
            options={
                'verbose_name': 'Стол',
                'verbose_name_plural': 'Столы',
                'ordering': ['is_free', 'place', 'table_num'],
            },
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Заказ столика', 'verbose_name_plural': 'Заказы столов'},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='is_free',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='place',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='table_num',
        ),
        migrations.AddField(
            model_name='reservation',
            name='places_amount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во мест на один стол'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='tables_amount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во столов'),
        ),
    ]
