# Generated by Django 3.2.4 on 2021-08-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_chef'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=40, verbose_name='Подзаголовок')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Отличие',
                'verbose_name_plural': 'Отличия',
            },
        ),
        migrations.CreateModel(
            name='GalleryFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото к галлерее',
                'verbose_name_plural': 'Фотографии продуктов галлереи',
            },
        ),
        migrations.CreateModel(
            name='GalleryRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото к галлерее',
                'verbose_name_plural': 'Фотографии ресторана в галлерее',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=20, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активность')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.ImageField(max_length=20, upload_to='', verbose_name='Заголовок')),
                ('description', models.CharField(max_length=30, verbose_name='Подзаголовок')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активность')),
            ],
        ),
    ]
