# Generated by Django 3.2.4 on 2021-08-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_feature_galleryfood_galleryrestaurant_news_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='image',
            field=models.ImageField(default='/static/PhotoNotFound', upload_to='images/features/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='galleryfood',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активность'),
        ),
        migrations.AddField(
            model_name='galleryrestaurant',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='image',
            field=models.ImageField(default='/static/PhotoNotFound', upload_to='images/chefs/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='galleryfood',
            name='image',
            field=models.ImageField(default='/static/PhotoNotFound', upload_to='images/gallery/foods/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='galleryrestaurant',
            name='image',
            field=models.ImageField(default='/static/PhotoNotFound', upload_to='images/gallery/restaurant', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='/static/PhotoNotFound', upload_to='images/news/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='/static/PhotoNotFound', upload_to='images/products/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(default='/static/PhotoNotFound', upload_to='images/sliders/', verbose_name='Фото'),
        ),
    ]
