# Generated by Django 3.2.4 on 2021-08-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_is_accept_chef_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдеры главного меню'},
        ),
        migrations.AddField(
            model_name='news',
            name='published_data',
            field=models.DateField(auto_now=True, verbose_name='Дата публикации'),
        ),
    ]
