# Generated by Django 3.2.4 on 2021-08-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_chef_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Заголовок'),
        ),
    ]
