# Generated by Django 3.2.4 on 2021-08-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_slider_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='about',
            field=models.CharField(max_length=150, verbose_name='О шефе'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(max_length=150, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Заголовок'),
        ),
    ]
