# Generated by Django 3.2.4 on 2021-08-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20210804_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.CharField(max_length=150, verbose_name='Подзаголовок'),
        ),
    ]
