# Generated by Django 3.2.4 on 2021-08-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_slider_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(max_length=150, verbose_name='Подзаголовок'),
        ),
    ]
