# Generated by Django 3.2.3 on 2021-08-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20210804_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(verbose_name='ID Клиента')),
                ('order', models.TextField(verbose_name='Продукты заказа')),
                ('phone', models.CharField(max_length=100, verbose_name='Номер телефона')),
                ('location', models.CharField(max_length=200, verbose_name='Локатион')),
                ('order_date', models.DateTimeField(auto_now=True, verbose_name='Дата заказа')),
                ('order_accept', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('is_delivered', models.BooleanField(default=True, verbose_name='Принят или нет')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
