# Generated by Django 3.2.3 on 2021-08-16 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_orderproducts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
