# Generated by Django 3.2.6 on 2021-09-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_auto_20210822_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category_slug',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
