# Generated by Django 3.2.6 on 2021-09-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_products_category_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
        migrations.AlterField(
            model_name='client',
            name='tel',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone'),
        ),
    ]
